### ISSUE TITLE
Add source headers?

### ISSUE THREAD

**Issue by hyandell** [OpenNMT/VisTools#2]
Could you add source headers to the files that contain MIT licensing? or relicense to Apache 2.0 to match the underlying Google work?

Also, is: "# Modified by Alexander Rush, 2007" a typo? ie) Should it have been 2017?

**Comment by guillaumekln** [comment]
Hello,

I added the MIT license in the file we contributed and fixed the modification date you referenced. Would that work for you?

**Comment by hyandell** [comment]
Looks good :)
